version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "--- Starting Build Phase ---"
      - echo "Navigating to app folder..."
      - cd my-java-app
      - echo "Compiling and Packaging Java Code..."
      - mvn clean package
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - my-java-app/target/*.war
  discard-paths: yes